export const ICONS = {
  HOME: 'home',
  EMPLOYEE: 'assignment_ind',
  CAR: 'airport_shuttle',
  PROCESS: 'account_tree',
  QUALITY_CHECKS: 'check_circle',
  FEET: 'folder_open',
  PARTS: 'pie_chart',
  DESCRIPTION: 'description',
  SEARCH: 'search',
  LABEL: 'label',
  ADD: 'add',
  PASSWORD: 'lock',
  CHECK: 'check_circle',
  UN_CHECK: 'radio_button_unchecked',
  VISIBILITY: 'visibility',
  VISIBILITY_OFF: 'visibility_off',
  EDIT: 'edit',
  REMOVE: 'delete',
  MANAGEMENT: 'splitscreen_landscape',
  ///CAR
  CAR_VIN: 'directions_car',
  CAR_STATUS: 'signal_wifi_statusbar_null',
  CAR_GENERATION: 'qr_code_2_add',
  CAR_RELEASE_YEAR: 'deployed_code',
  ///PART PRODUCTION
  PART_PRODUCTION: 'production_quantity_limits',
  ///MACHINE
  MACHINE: 'precision_manufacturing',
  MACHINE_TYPE: 'merge_type',
  MACHINE_STATUS: 'signal_cellular_null',
  MACHINE_LAST: 'history_2',
  //CHART
  PIE: 'data_usage',
  LINE: 'area_chart',
  POLAR: 'circle',
  //USER
  EMAIL: 'email',
  ROLE: 'badge',
  DEPARTMENT: 'business_center',
};
